"""add tts_url_to_interview_messages

Revision ID: 6cb2e0fe5db5
Revises: 5507d713a714
Create Date: 2025-11-30 22:13:30.237470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb2e0fe5db5'
down_revision: Union[str, None] = '5507d713a714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_messages', sa.Column('tts_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_messages', 'tts_url')
    # ### end Alembic commands ###
